version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/BlazorInteractive"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/tests/BlazorInteractive.Tests"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/tests/BlazorInteractive.IntegrationTests"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
